dependencies:
  - name: autonity
    repository: "file://helm-charts/autonity"
    version: 0.2.6
    condition: global.autonity.enabled
  - name: ethstats
    repository: "file://helm-charts/ethstats"
    version: 0.1.0
    condition: global.ethstats.enabled
  - name: prometheus
    repository: "@stable"
    version: 8.10.0
    condition: global.prometheus.enabled
  - name: grafana
    repository: "@stable"
    version: 3.3.5
    condition: global.grafana.enabled
