dependencies:
  - name: autonity
    version: 0.1.0
    condition: global.autonity.enabled
  - name: ethstats
    version: 0.1.0
    condition: global.ethstats.enabled
  - name: prometheus
    version: 0.1.0
    condition: global.prometheus.enabled
