---

global:
  autonity:
    enabled: true
  ethstats:
    enabled: false
    webSocketSecret: secret123

autonity:
  # Number of validators and observers
  validators: 4
  observers: 1

  chainid: 2019

ethstats:
  enabled: false