---
imageAutonity:
  repository: clearmatics/autonity
  tag: k8s-latest

imageAutonity_init:
  repository: clearmatics/autonity-init
  tag: v0.0.1

image_ibft_keys_generator:
  repository: clearmatics/ibft-keys-generator
  tag: v0.0.6

image_ibft_genesis_configurator:
  repository: clearmatics/ibft-genesis-configurator
  tag: v0.0.4

# Number of validators and observers
validators: 4
observers: 1

chainid: 2019
