---
imageAutonity:
  repository: clearmatics/autonity
  tag: latest

image_ibft_keys_generator:
  repository: clearmatics/ibft-keys-generator
  tag: v0.0.6

image_ibft_genesis_configurator:
  repository: clearmatics/ibft-genesis-configurator
  tag: v0.0.1

# Number of validators and observers
validators: 4
observers: 1

chainid: 2019
