---

global:
  autonity:
    enabled: true
  ethstats:
    enabled: false
    webSocketSecret: 3b7Lp5BDdtpNQyFwSjbtMHVU5Xuzo4
  prometheus:
    enabled: false


autonity:
  # Number of validators and observers
  validators: 4
  observers: 1
  chainid: 2019

prometheus:
  server:
    persistentVolume:
      enabled: false
    configMapOverrideName: 'prometheus-server-config'
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false
