---

global:
  autonity:
    enabled: true
  ethstats:
    enabled: false
    webSocketSecret: 3b7Lp5BDdtpNQyFwSjbtMHVU5Xuzo4

autonity:
  # Number of validators and observers
  validators: 4
  observers: 1
  chainid: 2019
