---

global:
  autonity-net:
    enabled: true
  ethstats:
    enabled: false

autonity-net:
  # Number of validators and observers
  validators: 4
  observers: 1

  chainid: 2019

ethstats:
  enabled: false