{
 "title": "Autonity",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "validator",
    "query": "geth_p2p_inboundTraffic_overall"
   },
   { "name": "metrics_list", "query": "metrics(geth_*)" }
  ]
 },
 "panels": [
  {
   "title": "Metrics for $validator",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$metrics_list{kubernetes_name=\"$validator\"}"
    }
   ]
  },
  {
   "title": "p2p traffic $validator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(geth_p2p_inboundTraffic_overall{kubernetes_name=\"$validator\"}[1m]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum(irate(geth_p2p_outboundTraffic_overall{kubernetes_name=\"$validator\"}[1m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "chain_write_overall $validator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(geth_chain_write_overall{kubernetes_name=\"$validator\"}[1m])",
     "legendFormat": "chain_write_overall"
    }
   ]
  }
 ]
}