---
# This ConfigMap will be used once as a template for generate genesis.json in initial step (as helm install hook)
# All enodeIDs, keys and extraData will replaced

apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-template
  namespace: {{ .Release.Namespace }}
data:
  genesis.json : |-
      {
          "config": {
              "homesteadBlock": 0,
              "eip150Block": 0,
              "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
              "eip155Block": 0,
              "eip158Block": 0,
              "byzantinumBlock": 0,
              "istanbul": {
                  "policy": 0,
                  "epoch": 30000,
                  "contract-deployer": "0x0000000000000000000000000000000000000001",
                  "bytecode": "",
              "abi": ""
              },
              "chainId": {{ .Values.chainid }},
          "glienickeDeployer": "0x0000000000000000000000000000000000000001",
              "glienickeBytecode": "",
              "glienickeABI": ""
          },
          "nonce": "0x0",
          "timestamp": "0x0",
          "gasLimit": "0x5F5E100",
          "difficulty": "0x1",
          "coinbase": "0x0000000000000000000000000000000000000000",
          "number": "0x0",
          "gasUsed": "0x0",
          "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365"
      }
