{{- $imageAutonity := .Values.imageAutonity -}}
{{- $imageAutonity_init := .Values.imageAutonity_init -}}
{{- $namespace := .Release.Namespace -}}

{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.validators))) }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: validator-{{ $i }}
  namespace: {{ $namespace }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-{{ $i }}
    spec:
      initContainers:
      - name: init
        image: {{ $imageAutonity_init.repository }}:{{ $imageAutonity_init.tag }}
        args:
          - "-type"
          - "validator"
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
        - name: keys
          mountPath: /autonity/keys
        - name: cm-genesis
          mountPath: /autonity/cm-genesis
        - name: sec-account-pwd
          mountPath: /autonity/sec-account-pwd
        - name: sec-validators
          mountPath: /autonity/sec-validators
      containers:
      - name: autonity
        image: {{ $imageAutonity.repository }}:{{ $imageAutonity.tag }}
        ports:
        - containerPort: 8545
          name: rpc
        - containerPort: 30303
          name: p2p
        args:
          - "--datadir"
          - "/autonity/blockchain"
          - "--keystore"
          - "/autonity/keys/keystore"
          - "--nodekey"
          - "/autonity/sec-validators/private_key"
          - "--syncmode"
          - "full"
          - "--cache"
          - "1024"
          - "--rpc"
          - "--rpcapi"
          - "eth,web3,net,txpool,debug"
          - "--rpcaddr"
          - "0.0.0.0"
          - "--ws"
          - "--wsaddr"
          - "0.0.0.0"
          - "--wsapi"
          - "eth,web3,net"
          - "--wsorigins"
          - "*"
          - "--metrics"
          - "--mine"
          - "--minerthreads"
          - "1"
          - "--debug"
          - "--verbosity"
          - "4"
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
        - name: keys
          mountPath: /autonity/keys
        - name: sec-validators
          mountPath: /autonity/sec-validators
      volumes:
        - name: blockchain
          emptyDir: {}
        - name: keys
          emptyDir:
            medium: Memory
            sizeLimit: "1M"
        - name: cm-genesis
          configMap:
            name: genesis
        - name: sec-account-pwd
          secret:
            secretName: account-pwd
        - name: sec-validators
          secret:
            secretName: validators
            items:
              - key: {{ $i }}.private_key
                path: private_key
{{- end}}

# /autonity/sec-validators/private_key
# /autonity/sec-account-pwd/account.pwd
# /autonity/cm-genesis/genesis.json
# /autonity/blockchain/
# /autonity/keys/
