{{- $imageAutonity := .Values.imageAutonity -}}
{{- $namespace := .Release.Namespace -}}

{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.validators))) }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: validator-{{ $i }}
  namespace: {{ $namespace }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-{{ $i }}
    spec:
      containers:
      - name: autonity
        image: {{ $imageAutonity.repository }}:{{ $imageAutonity.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8545
          name: rpc
        - containerPort: 30303
          name: p2p
{{- end}}
